### ISSUE TITLE
TODO: Add Chronograf Helm chart under CB-Dragonfly Helm chart

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-operator#120]
**What would you like to be added**
: 
Chronograf Helm chart under CB-Dragonfly Helm chart

**Why is this needed**
:
CB-Dragonfly 구동에 Chronograf 가 필요함

---

@seokho-son 님께서 [cb-operator/docker-compose-mode-files/docker-compose-df-only.yaml](https://github.com/cloud-barista/cb-operator/blob/master/docker-compose-mode-files/docker-compose-df-only.yaml) 에 추가하신
Chronograf 관련 내용을
[cb-operator/docker-compose-mode-files/docker-compose.yaml](https://github.com/cloud-barista/cb-operator/blob/master/docker-compose-mode-files/docker-compose.yaml) 에도 추가하는 PR (#119) 을 올렸습니다.

이제 Cloud-Barista 의 Helm chart 에도 Chronograf Helm chart 를 추가해야 합니다.

@hyokyungk @inno-cloudbarista 한 번 확인해 보시고, 진행을 해 주시면 감사하겠습니다.. ^^

**Comment by seokho-son** [comment]
@jihoon-seo 
Chronograf 는 CB-Dragonfly 의 개발 중, 간단한 확인을 위해서 사용하고 계십니다.
docker-compose-df-only.yaml 에는 간단히 시연을 위해서 제가 임시로 추가한 것입니다.

(현재는) 공식적인 지원 도구가 아니고 DF가 Chronograf에 의존성이 없으므로, 
docker-compose.yaml 에서는 제외하는 것이 바람직해 보입니다.

**Comment by jihoon-seo** [comment]
이 이슈는 클로즈 하고, 추후 필요성이 생기면 고려해 볼 수 있겠습니다.. ^^
