### ISSUE TITLE
Change variables to constants

### ISSUE THREAD

**Issue by computerphilosopher** [cloud-barista/cb-operator#152]
**What would you like to be enhanced**
: 

utility.go 파일에 보면 여러가지 문자열 변수들이 있습니다.

https://github.com/cloud-barista/cb-operator/blob/ff80817a253587ff6d271a9964ce6d0f60672dce/src/common/utility.go#L10-L41

그런데 이중에 상당수가 사실상 변수가 아닌 상수의 역할을 하고 있는 것으로 보입니다.

변경되지 않아야 하는 값이라면 상수로 바꾸는 것이 어떨까요?

**Why is this needed**
: 

코드 가독성 개선 및 실수로 인한 변경 가능성 제거 

**Proposed solution**
:
```go
const (
	ModeDockerCompose = "DockerCompose"
	ModeKubernetes    = "Kubernetes"
        // ....
)
```

**Comment by jihoon-seo** [comment]
@computerphilosopher 아주 좋은 의견이십니다!
이슈 남겨 주셔서 감사합니다. 😊
혹시 직접 기여도 가능하시다면, PR 작성해 주시면 정말 좋을 것 같구요.. 😊😊
