### ISSUE TITLE
File `calllog_conf.yaml` is missing on the helm chart (CB-Spider)

### ISSUE THREAD

**Issue by itnpeople** [cloud-barista/cb-operator#90]
CB-Spider Helm Chart [configmap](https://github.com/cloud-barista/cb-operator/blob/master/helm-chart/charts/cb-spider/templates/configmap.yaml) 정의 에서 
`calllog_conf.yaml` 파일이 빠져 있어 호출시 Crash 발생

**Comment by jihoon-seo** [comment]
Fixed by #92
